client_id = "391aeeccf003c4d8f67d87fb3d8ef6f4"
name = "EFRO Integration"
handle = "efro-integration"

# Wichtig: https + Port vom --use-localhost Proxy
application_url = "https://localhost:3458"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_script_tags,write_script_tags,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://localhost:3458/api/auth/callback/shopify"
]

[webhooks]
api_version = "2024-07"
